[package]
name = "figura-backend"
version = "0.1.0"
description = "Unofficial custom Figura server backend implementation."
edition = "2021"
authors = ["GlFolker"]
license = "Apache-2.0 OR MIT"

[dependencies]
actix-web = { version = "4", features = ["rustls-0_22"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rustls = "0.22"
rustls-pemfile = "2"
